version: '3'

services:
  db:
    image: mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ["./wait-for-it.sh", "mysql:3306", "--", "uvicorn", "app:app","--host","0.0.0.0","--reload"]
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt